/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "user": {
            "USER_ERR_001": string;
            "USER_ERR_002": string;
            "USER_ERR_003": string;
            "USER_ERR_004": string;
            "USER_ERR_005": string;
        };
    };
    "validation": {
        "email": {
            "EMAIL_ERR_001": string;
            "EMAIL_ERR_002": string;
        };
        "password": {
            "PASSWORD_ERR_001": string;
            "PASSWORD_ERR_002": string;
        };
        "first_name": {
            "FIRST_NAME_ERR_001": string;
            "FIRST_NAME_ERR_002": string;
        };
        "last_name": {
            "LAST_NAME_ERR_001": string;
            "LAST_NAME_ERR_002": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
