/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "USER": {
            "USER_ERR_001": string;
            "USER_ERR_002": string;
        };
    };
    "validation": {
        "EMAIL": {
            "EMAIL_ERR_001": string;
            "EMAIL_ERR_002": string;
        };
        "PASSWORD": {
            "PASSWORD_ERR_001": string;
            "PASSWORD_ERR_002": string;
        };
        "FIRST_NAME": {
            "FIRST_NAME_ERR_001": string;
            "FIRST_NAME_ERR_002": string;
        };
        "LAST_NAME": {
            "LAST_NAME_ERR_001": string;
            "LAST_NAME_ERR_002": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
